// A race: N cars, T teams, one circuit, and everything that happens between
// them.
//
// This is the environment a policy sees. One `RaceEnv` is one race; `VecRaceEnv`
// runs many of them side by side, which is the only way the throughput works --
// a policy step costs far less than a Python round trip, so what matters is how
// many races advance per call rather than how fast one of them runs.
//
// Every car in a race is an agent. They share an action space and, in the
// reference training loop, a policy; what separates them is which team they are
// on, and therefore whose result their reward depends on. See
// RewardConfig::team_weight, which is the dial that decides whether the field
// behaves like eight individuals or four teams of two.

#pragma once

#include <cstdint>
#include <functional>
#include <memory>
#include <string>
#include <vector>

#include "racing/car.hpp"
#include "racing/config.hpp"
#include "racing/interaction.hpp"
#include "racing/powertrain.hpp"
#include "racing/track.hpp"
#include "racing/tyres.hpp"
#include "racing/vehicle.hpp"

namespace racing {

// Something worth telling a viewer about. Produced by the environment, consumed
// by the feed -- the engine decides what happened, the renderer decides how to
// draw it.
struct RaceEvent {
  enum Type {
    OVERTAKE = 0,   // `car` took a place from `other`
    CONTACT = 1,    // `car` (behind/inside) touched `other`; `value` = severity
    OFF_TRACK = 2,  // `car` left the corridor
    REJOIN = 3,     // `car` came back on, or was recovered after being stranded
    LAP = 4,        // `car` completed lap `lap` in `value` seconds
    FINISH = 5,     // `car` took the flag in position `value`
    RETIRE = 6,     // `car` is out
  };

  int type = OVERTAKE;
  double time = 0.0;  // seconds since the start of the race
  int car = -1;
  int other = -1;
  double value = 0.0;
  int lap = 0;
  // Only set on RETIRE, where it is a RetireReason. A separate field rather
  // than an overload of `value`, which on a RETIRE event carries the damage the
  // car had accumulated -- both are worth knowing and neither implies the other.
  int reason = RETIRE_NONE;
};

// Per-race summary of a step, for logging and for the training loop's console
// output. Not part of any observation.
struct StepInfo {
  double race_time = 0.0;
  double leader_distance = 0.0;
  double mean_speed = 0.0;
  int n_contacts = 0;
  int n_overtakes = 0;
  int n_off_track = 0;
  int n_finished = 0;
  int n_retired = 0;
  double mean_damage = 0.0;
  bool done = false;
};

class RaceEnv {
 public:
  RaceEnv(EnvConfig cfg, std::shared_ptr<const Track> track, uint32_t env_idx);

  // `episode` keys every draw for this race alongside the config seed, so a
  // given (seed, env_idx, episode) always produces the same race.
  void reset(uint64_t episode);

  // One policy step for the whole field. `actions` is [n_cars, 2] --
  // (steer, throttle) per car -- held for `action_repeat` physics steps.
  // `rewards` is filled with [n_cars].
  void step(const float* actions, float* rewards, StepInfo* info);

  // `out` is [n_cars, obs_dim].
  void observe(float* out) const;
  int obs_dim() const;
  // Which of the two observations this environment publishes. Kept separate so
  // the layout can be read without inspecting the config.
  int observation_mode() const { return cfg_.observation.mode; }

  int n_cars() const { return n_cars_; }
  bool done() const { return done_; }
  int step_count() const { return step_count_; }
  double race_time() const { return race_time_; }
  double race_distance() const { return race_distance_; }

  const std::vector<CarState>& cars() const { return cars_; }
  const std::vector<int>& teams() const { return team_of_; }
  // Where the wing may be opened, worked out from the circuit at construction.
  const std::vector<DrsZone>& drs_zones() const { return drs_zones_; }
  double air_density() const { return air_density_; }
  const Track& track() const { return *track_; }
  const EnvConfig& config() const { return cfg_; }

  // Called at the end of every *physics* step, not every policy step. The feed
  // uses it to sample positions faster than the policy runs: the policy acts at
  // 25 Hz, which is too coarse to render from directly, while the physics runs
  // at 100 Hz and can be decimated to whatever the visualizer wants.
  //
  // Null by default, and checked before it is called, so training pays nothing
  // for it.
  using PhysicsObserver = std::function<void(const RaceEnv&)>;
  void set_observer(PhysicsObserver o) { observer_ = std::move(o); }

  // Events generated by the most recent step. Cleared at the start of each one,
  // so a caller that wants them all has to drain this every step -- which is
  // what the feed does.
  const std::vector<RaceEvent>& events() const { return events_; }

  // Finishing order as car indices, best first. Only meaningful once the race
  // is done, but always well defined.
  std::vector<int> finish_order() const;
  // Points-style team score: each car contributes (n_cars - position).
  std::vector<int> team_scores() const;

 private:
  void place_on_grid(uint32_t ep);
  void observe_sensor(float* out) const;
  void physics_step(double dt);
  void update_drs(CarState* c, double prev_s);
  double potential(double distance) const;
  void emit(int type, int car, int other, double value, int lap);
  // Take a car out of the race. Idempotent, so the several places that can
  // decide a car is finished do not have to coordinate.
  void retire(int car, int reason, int other);

  EnvConfig cfg_;
  std::shared_ptr<const Track> track_;
  Vehicle vehicle_;
  Powertrain powertrain_;
  std::vector<DrsZone> drs_zones_;
  double air_density_ = 0.0;
  uint32_t env_idx_ = 0;
  uint64_t episode_ = 0;
  int n_cars_ = 0;

  std::vector<CarState> cars_;
  std::vector<int> team_of_;
  std::vector<Contact> contacts_;
  std::vector<BarrierHit> barrier_hits_;
  std::vector<RaceEvent> events_;
  // Cars that retired during the current policy step, so the reward loop can
  // charge the penalty exactly once without re-scanning for newly-out cars.
  std::vector<int> just_retired_;

  // Pairs of cars that were touching at the end of the previous step, so a
  // sustained scrape reports as one contact rather than one per physics step.
  std::vector<uint64_t> prev_touching_;
  // Confirmed order of each pair of cars, +1 if i is ahead of j. Flipping it
  // needs a clear margin, so nose-to-tail jitter does not read as a pass.
  std::vector<int8_t> order_sign_;
  std::vector<int> prev_position_;
  std::vector<double> prev_potential_;
  std::vector<float> own_reward_;

  double race_time_ = 0.0;
  double race_distance_ = 0.0;
  bool done_ = false;
  int step_count_ = 0;
  int max_steps_ = 0;
  int n_finished_ = 0;
  PhysicsObserver observer_;
};

// Many races at once.
class VecRaceEnv {
 public:
  VecRaceEnv(const EnvConfig& cfg, int n_envs, int n_threads = 1);

  void reset_all(uint64_t episode);

  // `actions` is [n_envs, n_cars, 2]; `obs` is [n_envs, n_cars, obs_dim];
  // `rewards` is [n_envs, n_cars]; `dones` is [n_envs].
  //
  // Races that finish are reset automatically and their observation is the
  // first of the next race, which is the convention every vectorised RL
  // library expects.
  void step(const float* actions, float* obs, float* rewards, uint8_t* dones,
            StepInfo* infos = nullptr);

  void observe(float* obs) const;

  // Full per-car state, [n_envs, n_cars, STATE_FIELDS]. Deliberately not part
  // of the observation: a policy must never see another car's absolute
  // position, only what it could work out from where it is looking. This
  // exists for logging, for the visualizer feed, and for checking that a lap
  // stayed inside track limits -- which cannot be checked from the observation.
  enum StateField : int {
    STATE_X = 0, STATE_Y, STATE_Z, STATE_PSI, STATE_VX, STATE_VY, STATE_R,
    STATE_S, STATE_E_Y, STATE_DISTANCE, STATE_LAP, STATE_POSITION,
    STATE_DOWNFORCE, STATE_DRAG, STATE_GAP_AHEAD, STATE_TEAM,
    STATE_FIELDS
  };
  void states(float* out) const;

  int n_envs() const { return static_cast<int>(envs_.size()); }
  int n_cars() const { return envs_.empty() ? 0 : envs_[0]->n_cars(); }
  int obs_dim() const { return envs_.empty() ? 0 : envs_[0]->obs_dim(); }
  const Track& track() const { return *track_; }
  RaceEnv& env(int i) { return *envs_[i]; }
  const RaceEnv& env(int i) const { return *envs_[i]; }

 private:
  std::shared_ptr<const Track> track_;
  std::vector<std::unique_ptr<RaceEnv>> envs_;
  std::vector<uint64_t> episode_;
  int n_threads_ = 1;
};

}  // namespace racing
